### ISSUE TITLE
[ZEON] - recommended additions

### ISSUE THREAD

**Issue by zeon-neon** [NeonGamerBot-QK/crunchyroll-comments#8]
# Meta

- [ ] This repo does not have a code of conduct (feature is in beta!)

- [ ] if possible make your app docker compatible? (beta)

- [ ] if possible make your app docker compatible? (beta)

- [ ] undefined
# Automation

- [ ] **Mark this to override & close this issue.**
